# Generated by Django 4.2.7 on 2023-11-01 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogsysytem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='craeted_at',
            new_name='created_at',
        ),
    ]
